; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8EA051DC-0C50-4537-9C67-B77A3F3953C8}
AppName=Print PDF - Python
AppVersion=1.0
;AppVerName=PDF Print Py 1.0
AppPublisher=M.ROHAN FAROOQUI©
AppPublisherURL=https://rohanfarooqui.blogspot.com/
AppSupportURL=https://rohanfarooqui.blogspot.com/
AppUpdatesURL=https://rohanfarooqui.blogspot.com/
DefaultDirName={autopf}\Print PDF - Python
DisableProgramGroupPage=yes
; The [Icons] "quicklaunchicon" entry uses {userappdata} but its [Tasks] entry has a proper IsAdminInstallMode Check.
UsedUserAreasWarning=no
LicenseFile=C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\license.txt
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename=Print PDF Python 1.0 - Setup 
SetupIconFile=C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\setup.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\Print Pdf Python.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\api-ms-win-crt-heap-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\api-ms-win-crt-locale-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\api-ms-win-crt-math-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\api-ms-win-crt-runtime-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\api-ms-win-crt-stdio-l1-1-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\python38.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\Images\*"; DestDir: "{app}\Images"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\M.ROHAN FAROOQUI\Desktop\pritn pdf py\Print Pdf Py - Build 1.0\Build - 1.0\Print_Lib\*"; DestDir: "{app}\Print_Lib"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\PDF Print Py"; Filename: "{app}\Print Pdf Python.exe"
Name: "{autodesktop}\PDF Print Py"; Filename: "{app}\Print Pdf Python.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\PDF Print Py"; Filename: "{app}\Print Pdf Python.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\Print Pdf Python.exe"; Description: "{cm:LaunchProgram,PDF Print Py}"; Flags: nowait postinstall skipifsilent

